# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import formaggio.models


class Migration(migrations.Migration):

    dependencies = [
        ('formaggio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaggiofieldvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to=formaggio.models.get_form_file_upload_path),
        ),
    ]
